name: fimDosTemposWeekly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.5.0
  cloud_firestore: ^2.5.0
  firebase_database: ^7.2.1
  url_launcher: ^6.0.9
  firebase_messaging: ^10.0.7
  shared_preferences: ^2.0.7
  share_plus: ^3.0.1
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/papyrus.jpeg
    - assets/images/characters-banner.png
    - assets/images/histories-banner.png
    - assets/images/character-sheet.png
    - assets/images/bookmark.png
    - assets/images/page-divider.png
    - assets/images/twitch-alert.png
    - assets/images/arrow-right.png
    - assets/images/page-scroll.png
    - assets/images/tormenta-logo.png
    - assets/images/load-error.png
    - assets/images/image-error.png
    - assets/images/yt-icon.png
    - assets/images/jambo.jpg
    - assets/images/tormenta.png
    - assets/images/twitch.png
    - assets/images/twitter.png
    - assets/images/ignis.png
    - assets/images/ayla.png
    - assets/images/kiki.png
    - assets/images/arius.png
    - assets/images/rexthor.png

flutter_native_splash:
  color: '#741920'
  image: assets/images/FimDosTemposWeekly.png